language: go
go: 1.5

branches:
  only:
    - master
    - develop
    - /^feat(ure)?-.*$/
    - /^(hot)?fix-.*$/

install:
  - sudo apt-get update -q
  - sudo apt-get install -y vim-gtk
  - go get github.com/google/git-appraise/git-appraise 

before_script:
  - vim --version
  - git clone https://github.com/thinca/vim-themis
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
  - vim-themis/bin/themis --reporter dot test
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 plugin
